# version string format -- This will be overwritten later anyway
version: "{build}"

os:
  - Visual Studio 2017

skip_tags: true

configuration:
  - Release

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 14 2015
      VISUAL_STUDIO_INTERNAL_VERSION: 140
      VISUAL_STUDIO_VERSION: 14.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017
      VISUAL_STUDIO_INTERNAL_VERSION: 141
      VISUAL_STUDIO_VERSION: 14.1

matrix:
  fast_finish: true

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg integrate install
  - vcpkg install eigen3
  - vcpkg install opencv
  - vcpkg install pangolin

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build && cd build
  - cmake -G "%CMAKE_GENERATOR% Win64" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..

build_script:
  - cmake --build . --config %CONFIGURATION% -- /verbosity:minimal
